stages:
  - build
  - assemble
  - publish

variables:
  GOLANG_VERS: "1.18"
  GIT_TRACE: "0"
  GIT_DEPTH: "1"
  GIT_CURL_VERBOSE: "1"
  GIT_LFS_SKIP_SMUDGE: "1"
  GIT_STRATEGY: "clone"
  GIT_SUBMODULE_STRATEGY: recursive
  MINOR_VERSION: "2"
  TARGET_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_BRANCH
  VALIDATOR_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/validator:$CI_COMMIT_BRANCH
  RUST_VERSION: "1.89.0"

  # "cli" "accounts-bench" "accounts-cluster-bench" "banking-bench" "bench-streamer" "bench-tps" "dos" "faucet" "genesis" "gossip" "install" "install-init" "ip-address" "ip-address-server" "keygen" "ledger-tool" "ledger-udev" "log-analyzer" "merkle-root-bench" "net-shaper" "poh-bench" "stake-accounts" "store-tool" "test-validator" "tokens" "transaction-dos" "upload-perf" "validator" "watchtower" "zk-keygen"

build_tar:
  stage: assemble
  tags: ["d-3"]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "dev"
  image: ${CI_REGISTRY}/eflam/builder/compact:main-bookworm
  script:
    - git archive --format=tar HEAD >out.tar
  artifacts:
    expire_in: 1 hour
    paths:
      - ./out.tar

deploy_source:
  stage: publish
  tags: ["deploy", "bastion"]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "dev"
  variables:
    COMMIT_MSG: "doing update"
    # do not increase major version past 0 or else go list will fail
    AGAVE_BASE: "v3.1.5"
    TARGET_PROJECT: ${CI_PROJECT_NAME}
    TARGET_GIT_DIR: "/var/share/noncepad/git/${TARGET_PROJECT}.git"
  needs:
    - job: build_tar
      artifacts: true
  script:
    - /bin/bash ./contrib/remote-git.sh
