[package]
name = "catscope-zerohop"
version = "0.4.4"
edition = "2024"

[features]
capacity = ["dep:tonic", "dep:prost", "dep:tonic-build", "dep:tokio-stream"]

[build-dependencies]
tonic-build = { version = "0.12", optional = true }

[dependencies]
tonic = { version = "0.12", features = ["transport"], optional = true }
prost = { version = "0.13", optional = true }
tokio-stream = { version = "0.1", optional = true }
log = "0.4.29"
lockfree = "0.5.1"
env_logger = "0.11.8"
twox-hash = "2.1.2"
agave-geyser-plugin-interface = "=4.1.0-rc.1"
solana-sdk = "=4.0.0"
solana-pubkey = { version = "=4.2.0", features = ["curve25519"] }
flume = "0.11"
iceoryx2 = "0.6"
crossbeam-channel = "0.5.15"
crossbeam = "0.8.4"
serde = "1.0.228"
solana-client = "=4.1.0-rc.1"
solana-connection-cache = { version = "=4.1.0-rc.1", features = [
  "agave-unstable-api",
] }
solana-tpu-client = "=4.1.0-rc.1"
solana-quic-client = "=4.1.0-rc.1"
solana-streamer = "=4.1.0-rc.1"
tokio = { version = "1.44", features = ["full"] }
bincode = "1.3"
signal-hook = "0.3"
wincode = { version = "0.3.1", features = ["derive"] }

[dev-dependencies]
num_cpus = "1.17.0"

[[bin]]
name = "catfwd"
path = "src/bin/catfwd.rs"

[package.metadata.deb]
maintainer = "Joel De Jesus <joel@noncepad.com>"
assets = [["./target/release/catfwd", "/usr/bin/catfwd", "0755"]]

[patch.crates-io]
agave-geyser-plugin-interface = { git = "https://git.noncepad.com/solana.git", tag = "v4.1.0-rc.1-catscope" }
solana-client = { git = "https://git.noncepad.com/solana.git", tag = "v4.1.0-rc.1-catscope" }
solana-connection-cache = { git = "https://git.noncepad.com/solana.git", tag = "v4.1.0-rc.1-catscope" }
solana-tpu-client = { git = "https://git.noncepad.com/solana.git", tag = "v4.1.0-rc.1-catscope" }
solana-quic-client = { git = "https://git.noncepad.com/solana.git", tag = "v4.1.0-rc.1-catscope" }
solana-streamer = { git = "https://git.noncepad.com/solana.git", tag = "v4.1.0-rc.1-catscope" }
